emqx:
    persistence:
      enabled: true
    emqxConfig:
      EMQX_CLUSTER__K8S__APISERVER: "https://kubernetes.default.svc:443"
      ## The address type is used to extract host from k8s service.
      ## Value: ip | dns | hostname
      ## Note：Hostname is only supported after v4.0-rc.2
      EMQX_CLUSTER__K8S__ADDRESS_TYPE: "hostname"
      EMQX_CLUSTER__K8S__SUFFIX: "svc.cluster.local"
      ## if EMQX_CLUSTER__K8S__ADDRESS_TYPE eq dns
      # EMQX_CLUSTER__K8S__SUFFIX: "pod.cluster.local"
